kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      env: canary
  template:
    metadata:
      labels:
        env: canary
    spec:
      containers:
      - name: frontend
        image: sample-app-frontend
        env:
        - name: VERSION
          value: canary
        - name: BACKEND_URL
          value: http://gceme-backend-prod:8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
