apiVersion: cloudDeploy/beta1
kind: delivery-pipeline
name: web-app
description: web-app delivery pipeline
serialPipeline:
 stages:
 - targetId: staging
   profiles:
   - staging
 - targetId: prod
   profiles:
   - prod
---
apiVersion: cloudDeploy/beta1
kind: target
name: staging
deliveryPipeline: web-app
description: staging
gkeCluster:
  project: vic-e2e-cicd
  cluster: staging
  location: us-west2
---
apiVersion: cloudDeploy/beta1
kind: target
name: prod
deliveryPipeline: web-app
description: prod
gkeCluster:
  project: vic-e2e-cicd
  cluster: prod
  location: us-west2

