apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: frontend
requires:
  - path: ../validate
  - path: ../backend
build:
  artifacts:
  - image: sample-app-frontend
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod
portForward:
  - resourceType: service
    resourceName: gceme-frontend-dev
    namespace: default
    port: 8080
