kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-frontend
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: frontend
        image: sample-app-frontend
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: dev
        - name: BACKEND_URL
          value: http://gceme-backend-dev:8080
