kind: Service
apiVersion: v1
metadata:
  name: gceme-frontend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: gceme
    role: frontend
